services:

  # ======================
  # PostgreSQL (Metadata)
  # ======================
  postgres:
    image: postgres:15.15
    container_name: lakehouse-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lakehouse-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  # ======================
  # MinIO (Data Lake)
  # ======================
  minio:
    image: minio/minio:RELEASE.2025-02-03T21-03-04Z-cpuv1
    container_name: lakehouse-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"   # API (pode ir atrÃ¡s de proxy depois)
      - "9001:9001" # Console (restrito)
    networks:
      - lakehouse-net
    restart: always

  # ======================
  # Spark
  # ======================
  spark-master:
    image: apache/spark:3.5.3
    container_name: spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "7077:7077"
      - "8088:8088"
    networks:
      - lakehouse-net
    restart: always

  spark-worker:
    image: apache/spark:3.5.3
    container_name: spark-worker
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - lakehouse-net
    restart: always

  # ======================
  # Trino
  # ======================
  trino:
    image: trinodb/trino:445
    container_name: lakehouse-trino
    ports:
      - "8081:8081"
    networks:
      - lakehouse-net
    restart: always

  # ======================
  # Airflow - INIT
  # ======================
  airflow-init:
    image: lakehouse-airflow:2.9.3
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow-init
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      bash -c "
      airflow db migrate &&
      airflow users create --username airflow --password airflow --firstname airflow --lastname User --role Admin --email admin@airflow.local
      "
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    networks:
      - lakehouse-net
    restart: "no"

  # ======================
  # Airflow - Webserver
  # ======================
  airflow-webserver:
    image: lakehouse-airflow:2.9.3
    container_name: airflow-webserver
    command: webserver
    env_file:
      - .env
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    ports:
      - "8082:8082"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    networks:
      - lakehouse-net
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8082/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

  # ======================
  # Airflow - Scheduler
  # ======================
  airflow-scheduler:
    image: lakehouse-airflow:2.9.3
    container_name: airflow-scheduler
    command: scheduler
    env_file:
      - .env
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    networks:
      - lakehouse-net
    healthcheck:
      test: ["CMD", "airflow", "jobs", "check", "--job-type", "SchedulerJob"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

# ======================
# Volumes
# ======================
volumes:
  postgres_data:
  minio_data:

# ======================
# Network
# ======================
networks:
  lakehouse-net:
    driver: bridge
